export const dummyData = [
	{ id: 1, name: "John", lastName: "Doe", job: "Engineer" },
	{ id: 2, name: "Jane", lastName: "Smith", job: "Doctor" },
	{ id: 3, name: "Michael", lastName: "Johnson", job: "Teacher" },
	{ id: 4, name: "Emily", lastName: "Davis", job: "Designer" },
	{ id: 5, name: "Daniel", lastName: "Martinez", job: "Programmer" },
	{ id: 6, name: "Sophia", lastName: "Garcia", job: "Lawyer" },
	{ id: 7, name: "James", lastName: "Rodriguez", job: "Chef" },
	{ id: 8, name: "Olivia", lastName: "Lopez", job: "Photographer" },
	{ id: 9, name: "David", lastName: "Gonzalez", job: "Architect" },
	{ id: 10, name: "Mia", lastName: "Wilson", job: "Artist" },
	{ id: 11, name: "Ethan", lastName: "Anderson", job: "Writer" },
	{ id: 12, name: "Charlotte", lastName: "Thomas", job: "Nurse" },
	{ id: 13, name: "Benjamin", lastName: "Taylor", job: "Plumber" },
	{ id: 14, name: "Amelia", lastName: "Moore", job: "Engineer" },
	{ id: 15, name: "Lucas", lastName: "Jackson", job: "Scientist" },
	{ id: 16, name: "Harper", lastName: "White", job: "Dentist" },
	{ id: 17, name: "Liam", lastName: "Harris", job: "Mechanic" },
	{ id: 18, name: "Evelyn", lastName: "Clark", job: "Therapist" },
	{ id: 19, name: "Mason", lastName: "Lewis", job: "Accountant" },
	{ id: 20, name: "Avery", lastName: "Walker", job: "Veterinarian" },
	{ id: 21, name: "Elijah", lastName: "Hall", job: "Pilot" },
	{ id: 22, name: "Lily", lastName: "Young", job: "Chef" },
	{ id: 23, name: "Henry", lastName: "King", job: "Musician" },
	{ id: 24, name: "Abigail", lastName: "Scott", job: "Journalist" },
	{ id: 25, name: "Jack", lastName: "Green", job: "Data Scientist" },
];
